import type { ChecklistSection } from '../../types/checklist'
import { LINKS } from '../externalLinks'

export const jeonsaMoveSections: ChecklistSection[] = [
  {
    id: 'plan',
    title: '이사 계획 수립',
    items: [
      {
        id: 'contract-end-date',
        title: '현재 임대차계약 종료일 확인',
        why: '계약 갱신 여부를 판단하고 퇴거 일정을 조율하기 위해 먼저 확인합니다.',
        how: ['기존 임대차계약서 확인'],
        cost: '없음',
        checks: ['계약 종료일', '갱신청구권 사용 여부', '자동 갱신 여부'],
        links: [],
      },
      {
        id: 'termination-notice',
        title: '계약 해지 통보',
        why: '해지 통보를 하지 않으면 묵시적 갱신이 되어 보증금 반환이 늦어질 수 있습니다.',
        how: ['문자 또는 카카오톡으로 통보', '확실하게 하려면 내용증명 발송'],
        cost: '무료 (내용증명 발송 시 별도 비용)',
        checks: ['계약 종료 2~6개월 전 통보', '통보 내역 보관', '임대인 수신 확인'],
        links: [],
        important: true,
      },
    ],
  },
  {
    id: 'existing-loan',
    title: '기존 전세대출 확인',
    items: [
      {
        id: 'loan-repay-method',
        title: '전세대출 상환 방식 확인',
        why: '보증금 반환 시 대출 상환 절차와 중도상환수수료 여부를 미리 파악합니다.',
        how: ['대출 은행에 직접 문의'],
        cost: '무료',
        checks: ['상환 방식', '중도상환수수료 여부', '대출 만기일'],
        links: [],
      },
      {
        id: 'target-change',
        title: '목적물 변경 가능 여부 확인',
        why: '기존 저금리 대출을 새 집에서도 유지할 수 있는지 확인합니다.',
        how: ['은행 문의', '보증기관(HUG/HF) 문의'],
        cost: '무료',
        checks: ['목적물 변경 가능 여부', '현재 소득 재심사 여부', '추가 대출 가능 여부'],
        links: [LINKS.HUG, LINKS.HF],
      },
    ],
  },
  {
    id: 'existing-insurance',
    title: '기존 보증보험 확인',
    items: [
      {
        id: 'insurance-cancel',
        title: '보증보험 해지 절차 확인',
        why: '이사 시 기존 보증보험 계약을 종료 처리해야 하며 환급금 여부도 확인합니다.',
        how: ['HUG 또는 HF 홈페이지에서 확인', '가입한 은행 문의'],
        cost: '없음',
        checks: ['해지 절차', '환급 여부'],
        links: [LINKS.HUG, LINKS.HF],
      },
    ],
  },
  {
    id: 'new-contract-prep',
    title: '새 집 계약 전',
    items: [
      {
        id: 'new-loan-check',
        title: '대출 가능 여부 확인',
        why: '계약금을 넣기 전 대출 가능 여부를 먼저 확인해야 계약금 손실을 방지할 수 있습니다.',
        how: ['은행 상담', '사전심사 신청'],
        cost: '무료',
        checks: ['총 대출 가능 금액', '예상 금리', '목적물 변경 가능 여부', '추가 대출 가능 여부'],
        links: [],
      },
      {
        id: 'deposit-return-schedule',
        title: '기존 집 보증금 반환 일정 확인',
        why: '잔금일에 자금 공백이 생기지 않도록 기존 보증금 반환 일정을 맞춰야 합니다.',
        how: ['기존 임대인에게 확인'],
        cost: '없음',
        checks: ['반환 예정일', '반환 계좌', '반환 방법'],
        links: [],
      },
    ],
  },
  {
    id: 'new-contract',
    title: '새 집 계약',
    items: [
      {
        id: 'new-registry',
        title: '등기부등본 확인',
        why: '새 집의 권리관계를 확인합니다.',
        how: ['인터넷등기소에서 발급'],
        cost: '약 700원',
        checks: ['소유자 확인', '근저당 확인', '압류 여부'],
        links: [LINKS.IROS],
        important: true,
      },
      {
        id: 'new-contract-review',
        title: '계약서 확인 (특약)',
        why: '대출 특약과 보증보험 특약이 포함되어야 계약금이 보호됩니다.',
        how: ['계약서 초안 사전 확인'],
        cost: '없음',
        checks: ['대출 특약', '보증보험 특약', '잔금일'],
        links: [],
      },
    ],
  },
  {
    id: 'vacate-prep',
    title: '퇴거 준비',
    items: [
      {
        id: 'restoration',
        title: '원상복구 범위 확인',
        why: '퇴거 시 보증금에서 공제되는 항목을 미리 임대인과 협의합니다.',
        how: ['임대인과 사전 협의'],
        cost: '상황에 따라 상이',
        checks: ['벽지 훼손', '못 자국', '파손 시설'],
        links: [],
      },
      {
        id: 'photo-record',
        title: '집 상태 촬영',
        why: '퇴거 시 보증금 분쟁을 방지하기 위해 현재 상태를 사진·영상으로 기록합니다.',
        how: ['전체 공간 사진 촬영', '영상 촬영'],
        cost: '무료',
        checks: ['전체 공간 촬영', '옵션 비품 촬영', '계량기 촬영'],
        links: [],
      },
    ],
  },
  {
    id: 'balance-day',
    title: '잔금일',
    items: [
      {
        id: 'deposit-return',
        title: '기존 집 보증금 반환 확인',
        why: '보증금이 입금되지 않으면 새 집 잔금을 치를 수 없습니다. 반드시 순서를 확인하세요.',
        how: ['계좌 입금 확인'],
        cost: '없음',
        checks: ['보증금 입금 확인', '공제 내역 확인'],
        links: [],
        important: true,
      },
      {
        id: 'loan-repay',
        title: '전세대출 상환 확인',
        why: '보증금 수령 후 대출 상환이 이루어져야 합니다.',
        how: ['은행 확인'],
        cost: '없음',
        checks: ['상환 완료 여부', '잔액 확인'],
        links: [],
      },
      {
        id: 'new-registry-recheck',
        title: '새 집 등기부등본 재확인',
        why: '계약 이후 잔금 전 사이에 권리관계가 바뀌었을 수 있습니다.',
        how: ['인터넷등기소에서 재발급'],
        cost: '약 700원',
        checks: ['신규 근저당 여부', '신규 압류 여부'],
        links: [LINKS.IROS],
        important: true,
      },
    ],
  },
  {
    id: 'move-in-day',
    title: '입주 당일',
    items: [
      {
        id: 'resident-registration',
        title: '전입신고',
        why: '전입신고를 해야 대항력이 발생합니다.',
        how: ['정부24 온라인 신청', '주민센터 방문'],
        cost: '무료',
        checks: ['전입신고 완료'],
        links: [LINKS.GOV24],
      },
      {
        id: 'fixed-date',
        title: '확정일자',
        why: '우선변제권 확보를 위해 전입신고와 함께 당일 처리합니다.',
        how: ['주민센터 방문'],
        cost: '약 600원',
        checks: ['확정일자 완료'],
        links: [LINKS.IROS],
      },
      {
        id: 'maintenance-settlement',
        title: '관리비 정산',
        why: '이전 세입자 사용분과 내 사용분을 명확하게 구분합니다.',
        how: ['관리사무소 확인', '계량기 직접 확인'],
        cost: '없음',
        checks: ['전기 검침', '수도 검침', '가스 검침', '관리비 미납 여부'],
        links: [],
      },
    ],
  },
  {
    id: 'after-move-in',
    title: '입주 이후',
    items: [
      {
        id: 'new-insurance',
        title: '새 전세보증보험 가입',
        why: '보증금 보호를 위해 입주 후 가능한 빨리 가입합니다.',
        how: ['HUG 또는 HF 홈페이지', '취급 은행 창구'],
        cost: '상품별 상이',
        checks: ['가입 완료', '보증서 수령'],
        links: [LINKS.HUG, LINKS.HF],
      },
    ],
  },
]
