import type { ChecklistSection } from '../../types/checklist'
import { LINKS } from '../externalLinks'

export const monthlyMoveSections: ChecklistSection[] = [
  {
    id: 'plan',
    title: '이사 계획 수립',
    items: [
      {
        id: 'contract-end-date',
        title: '현재 임대차계약 종료일 확인',
        why: '계약 종료일을 파악해야 이사 일정을 계획할 수 있습니다.',
        how: ['기존 임대차계약서 확인'],
        cost: '없음',
        checks: ['계약 종료일', '자동 갱신 여부', '갱신청구권 사용 여부'],
        links: [],
      },
      {
        id: 'termination-notice',
        title: '계약 해지 통보',
        why: '해지 통보를 하지 않으면 묵시적 갱신이 되어 보증금 반환이 늦어집니다.',
        how: ['문자 또는 카카오톡으로 통보', '확실하게 하려면 내용증명 발송'],
        cost: '무료 (내용증명 발송 시 별도 비용)',
        checks: ['계약 종료 2~6개월 전 통보', '통보 내용 보관', '임대인 수신 확인'],
        links: [],
        important: true,
        showWhen: { exitType: ['expired'] },
      },
      {
        id: 'early-exit-agreement',
        title: '중도퇴실 합의',
        why: '계약 기간 중 퇴실 시 임대인 동의 없이는 위약금이 발생하거나 보증금 반환이 어려울 수 있습니다.',
        how: ['임대인에게 퇴실 의향 사전 통보', '후임 세입자 구하기 협의', '위약금 조건 확인'],
        cost: '상황에 따라 위약금 발생 가능',
        checks: ['임대인 동의 확인', '위약금 조건 확인', '후임 세입자 구하기 여부', '퇴실 예정일 합의'],
        links: [],
        important: true,
        showWhen: { exitType: ['early'] },
      },
    ],
  },
  {
    id: 'existing-jeonse',
    title: '기존 전세 퇴거 준비',
    showWhen: { currentHousing: ['jeonse'] },
    items: [
      {
        id: 'jeonse-loan-repay',
        title: '전세대출 상환 방식 확인',
        why: '보증금 반환 시 대출 상환 절차와 중도상환수수료 여부를 미리 파악합니다.',
        how: ['대출 은행에 직접 문의'],
        cost: '무료',
        checks: ['상환 방식', '중도상환수수료 여부', '대출 만기일'],
        links: [],
      },
      {
        id: 'jeonse-insurance-cancel',
        title: '전세보증보험 해지 절차 확인',
        why: '이사 시 기존 보증보험 계약을 종료 처리해야 하며 환급금 여부도 확인합니다.',
        how: ['HUG 또는 HF 홈페이지에서 확인', '가입한 은행 문의'],
        cost: '없음',
        checks: ['해지 절차', '환급 여부'],
        links: [LINKS.HUG, LINKS.HF],
      },
    ],
  },
  {
    id: 'search-house',
    title: '새 집 알아보기',
    items: [
      {
        id: 'realtor-check',
        title: '공인중개사 자격 확인',
        why: '무등록 중개업소와의 거래를 방지합니다.',
        how: ['중개사무소 등록증 확인', '브이월드에서 등록 여부 조회'],
        cost: '무료',
        checks: ['등록증 게시 여부', '개업공인중개사 성명', '등록 상태 정상 여부'],
        links: [LINKS.VWORLD],
      },
      {
        id: 'environment-check',
        title: '주변 환경 확인',
        why: '실제 거주 만족도에 큰 영향을 미칩니다. 낮과 밤 모두 방문해보세요.',
        how: ['직접 방문 (낮·밤 시간대 모두)'],
        cost: '없음',
        checks: ['대중교통 접근성', '편의점', '마트', '병원', '치안 상태', '소음 여부'],
        links: [],
      },
      {
        id: 'house-condition',
        title: '집 상태 확인',
        why: '입주 후 하자 분쟁을 방지하기 위해 방문 시 꼼꼼하게 확인합니다.',
        how: ['현장 직접 방문'],
        cost: '없음',
        checks: ['누수 흔적', '곰팡이', '결로', '창문 상태', '방충망', '수도 수압', '온수', '보일러', '에어컨', '냉장고', '세탁기'],
        links: [],
      },
      {
        id: 'maintenance-fee',
        title: '관리비 확인',
        why: '월세 외 고정 지출인 관리비 구성을 미리 파악해야 실제 월 비용을 계산할 수 있습니다.',
        how: ['임대인 또는 중개사에게 문의'],
        cost: '없음',
        checks: ['월 관리비', '수도 포함 여부', '인터넷 포함 여부', '주차 포함 여부', '전기료 별도 여부', '가스비 별도 여부'],
        links: [],
      },
      {
        id: 'parking-check',
        title: '주차 가능 여부',
        why: '차량 보유 시 주차 가능 여부와 추가 비용을 사전에 확인합니다.',
        how: ['관리사무소 또는 임대인에게 문의'],
        cost: '없음',
        checks: ['주차 가능 여부', '주차 등록 필요 여부', '추가 비용 여부'],
        links: [],
      },
    ],
  },
  {
    id: 'before-contract',
    title: '계약 전',
    items: [
      {
        id: 'registry',
        title: '등기부등본 확인',
        why: '실제 소유자와 권리관계를 확인합니다.',
        how: ['인터넷등기소에서 발급'],
        cost: '약 700원',
        checks: ['소유자 확인', '근저당 확인', '압류 여부', '가압류 여부'],
        links: [LINKS.IROS],
        important: true,
      },
      {
        id: 'building-ledger',
        title: '건축물대장 확인',
        why: '불법건축물 여부를 확인합니다.',
        how: ['정부24에서 발급'],
        cost: '무료',
        checks: ['위반건축물 여부', '건물 용도 확인'],
        links: [LINKS.GOV24],
      },
      {
        id: 'contract-preview',
        title: '계약서 사전 확인',
        why: '계약 당일 조건이 바뀌는 것을 방지하고 특약을 미리 검토합니다.',
        how: ['공인중개사에게 초안 요청'],
        cost: '무료',
        checks: ['보증금', '월세', '관리비', '계약기간', '특약사항'],
        links: [],
      },
    ],
  },
  {
    id: 'contract-day',
    title: '계약 당일',
    items: [
      {
        id: 'lessor-check',
        title: '임대인 신원 확인',
        why: '실제 소유자와 계약하는지 확인합니다.',
        how: ['신분증 확인', '등기부등본 대조'],
        cost: '무료',
        checks: ['신분증 확인', '등기부등본 소유자 일치'],
        links: [],
      },
      {
        id: 'agent-check',
        title: '대리인 계약 여부 확인',
        why: '무권대리 위험을 방지합니다.',
        how: ['위임장 확인', '인감증명서 확인'],
        cost: '무료',
        checks: ['위임장 원본', '인감증명서 원본', '위임인 정보'],
        links: [],
      },
      {
        id: 'special-clause',
        title: '특약 확인',
        why: '반려동물, 흡연, 원상복구 범위 등 분쟁이 잦은 항목을 계약서에 명확히 기재합니다.',
        how: ['계약서 특약란 검토'],
        cost: '무료',
        checks: ['반려동물 가능 여부', '흡연 가능 여부', '원상복구 범위', '중도퇴실 조건', '월세 납부일', '월세 연체 시 조건'],
        links: [],
      },
    ],
  },
  {
    id: 'vacate-prep',
    title: '퇴거 준비',
    items: [
      {
        id: 'moving-company',
        title: '이사 업체 예약',
        why: '원하는 날짜를 확보하려면 미리 예약해야 합니다.',
        how: ['이사업체 비교 견적 후 예약'],
        cost: '업체별 상이',
        checks: ['방문 견적', '추가 비용 여부', '사다리차 필요 여부'],
        links: [],
      },
      {
        id: 'restoration',
        title: '원상복구 범위 확인',
        why: '보증금 공제를 최소화하기 위해 임대인과 미리 협의합니다.',
        how: ['임대인과 협의'],
        cost: '상황에 따라 상이',
        checks: ['벽지 훼손', '못 자국', '파손 시설'],
        links: [],
      },
      {
        id: 'photo-record',
        title: '퇴거 전 집 상태 촬영',
        why: '퇴거 시 보증금 분쟁을 방지하기 위해 사진·영상으로 기록합니다.',
        how: ['전체 공간 촬영', '영상 촬영'],
        cost: '무료',
        checks: ['전체 공간 촬영', '옵션 비품 촬영', '계량기 촬영'],
        links: [],
      },
    ],
  },
  {
    id: 'before-move-in',
    title: '입주 전',
    items: [
      {
        id: 'registry-recheck',
        title: '등기부등본 재확인',
        why: '계약 후 권리관계가 바뀌었을 수 있습니다.',
        how: ['인터넷등기소에서 재발급'],
        cost: '약 700원',
        checks: ['신규 근저당 여부', '신규 압류 여부', '계약 당시와 동일한 상태인지'],
        links: [LINKS.IROS],
        important: true,
      },
      {
        id: 'final-condition',
        title: '집 상태 최종 점검',
        why: '입주 전 하자를 확인합니다.',
        how: ['현장 직접 방문'],
        cost: '무료',
        checks: ['누수', '곰팡이', '보일러', '수도', '전기', '옵션 정상 작동'],
        links: [],
      },
    ],
  },
  {
    id: 'move-in-day',
    title: '입주 당일',
    items: [
      {
        id: 'resident-registration',
        title: '전입신고',
        why: '전입신고를 해야 대항력이 발생합니다.',
        how: ['정부24 온라인 신청', '주민센터 방문'],
        cost: '무료',
        checks: ['전입신고 완료'],
        links: [LINKS.GOV24],
      },
      {
        id: 'maintenance-settlement',
        title: '관리비 정산 확인',
        why: '이전 세입자 사용분과 내 사용분을 구분합니다.',
        how: ['관리사무소 확인', '계량기 직접 확인'],
        cost: '없음',
        checks: ['전기 검침', '수도 검침', '가스 검침', '미납 관리비 여부'],
        links: [],
      },
      {
        id: 'key-handover',
        title: '열쇠 및 비밀번호 인수',
        why: '정상 입주에 필요한 모든 접근 수단을 확인합니다.',
        how: ['임대인 또는 관리사무소로부터 인수'],
        cost: '없음',
        checks: ['현관 열쇠', '공동현관 비밀번호', '우편함 비밀번호', '주차 등록 여부'],
        links: [],
      },
    ],
  },
  {
    id: 'vacate-day',
    title: '퇴거 당일',
    items: [
      {
        id: 'deposit-return',
        title: '보증금 반환 확인',
        why: '보증금을 제때 돌려받지 못하면 임차권등기명령 등의 절차가 필요할 수 있습니다.',
        how: ['계좌 입금 확인'],
        cost: '없음',
        checks: ['보증금 입금 확인', '공제 내역 확인', '영수증 수령 여부'],
        links: [],
        important: true,
      },
    ],
  },
]
