import type { ChecklistSection } from '../../types/checklist'
import { LINKS } from '../externalLinks'

export const moveSections: ChecklistSection[] = [
  {
    id: 'plan',
    title: '이사 계획 수립',
    items: [
      {
        id: 'sell-plan',
        title: '현재 주택 매도 계획 수립',
        why: '매도 일정이 이사 일정과 맞지 않으면 자금 공백이 생길 수 있습니다.',
        how: ['공인중개사와 매도 시세·일정 협의', '국토부 실거래가·KB부동산으로 시세 파악'],
        cost: '무료',
        checks: ['목표 매도가', '예상 매도 일정', '이사할 집 잔금일과 조율'],
        links: [LINKS.MOLIT, LINKS.KB],
        showWhen: { currentHousing: ['maemae'] },
      },
      {
        id: 'contract-end-date',
        title: '현재 임대차계약 종료일 확인',
        why: '계약 종료일을 파악해야 이사 일정을 계획하고 통보 시점을 맞출 수 있습니다.',
        how: ['기존 임대차계약서 확인'],
        cost: '없음',
        checks: ['계약 종료일', '자동 갱신 여부', '갱신청구권 사용 여부'],
        links: [],
        showWhen: { currentHousing: ['monthly', 'jeonse'] },
      },
      {
        id: 'termination-notice',
        title: '계약 해지 통보',
        why: '해지 통보를 하지 않으면 묵시적 갱신이 되어 보증금 반환이 늦어집니다.',
        how: ['문자 또는 카카오톡으로 통보', '확실하게 하려면 내용증명 발송'],
        cost: '무료 (내용증명 발송 시 별도 비용)',
        checks: ['계약 종료 2~6개월 전 통보', '통보 내용 보관', '임대인 수신 확인'],
        links: [],
        important: true,
        showWhen: { currentHousing: ['monthly', 'jeonse'], exitType: ['expired'] },
      },
      {
        id: 'early-exit-agreement',
        title: '중도퇴실 합의',
        why: '계약 기간 중 퇴실 시 임대인 동의 없이는 위약금이 발생하거나 보증금 반환이 어려울 수 있습니다.',
        how: ['임대인에게 퇴실 의향 사전 통보', '후임 세입자 구하기 협의', '위약금 조건 확인'],
        cost: '상황에 따라 위약금 발생 가능',
        checks: ['임대인 동의 확인', '위약금 조건 확인', '후임 세입자 구하기 여부', '퇴실 예정일 합의'],
        links: [],
        important: true,
        showWhen: { currentHousing: ['monthly', 'jeonse'], exitType: ['early'] },
      },
    ],
  },
  {
    id: 'current-maemae-sell',
    title: '현재 주택 매도',
    showWhen: { currentHousing: ['maemae'] },
    items: [
      {
        id: 'capital-gains-tax',
        title: '양도세 계산 및 비과세 요건 확인',
        why: '1세대 1주택 비과세 요건(2년 보유·거주 등)을 충족하지 못하면 양도세가 크게 부과될 수 있습니다.',
        how: ['국세청 홈택스 양도세 계산기 이용', '세무사 상담 (복잡한 경우)'],
        cost: '무료 (세무사 상담 시 별도)',
        checks: ['보유 기간 확인', '거주 기간 확인', '비과세 요건 충족 여부', '예상 양도세'],
        links: [LINKS.HOMETAX],
        important: true,
      },
      {
        id: 'tenant-eviction-plan',
        title: '임차인 명도 계획',
        why: '현재 집에 세입자가 있다면 매수인에게 집을 넘기기 전 명도를 완료해야 합니다.',
        how: ['임차인과 명도 일정 사전 협의', '명도 합의서 작성', '이사비 지원 협의'],
        cost: '협의에 따라 상이',
        checks: ['임차인 유무 확인', '명도 완료 예정일', '매수인과 일정 조율'],
        links: [],
        showWhen: { currentHousing: ['maemae'] },
      },
    ],
  },
  {
    id: 'current-jeonse-exit',
    title: '현재 전세 정리',
    showWhen: { currentHousing: ['jeonse'] },
    items: [
      {
        id: 'loan-repay-method',
        title: '전세대출 상환 방식 확인',
        why: '보증금 반환 시 대출 상환 절차와 중도상환수수료 여부를 미리 파악합니다.',
        how: ['대출 은행에 직접 문의'],
        cost: '무료',
        checks: ['상환 방식', '중도상환수수료 여부', '대출 만기일'],
        links: [],
      },
      {
        id: 'target-change',
        title: '전세대출 목적물 변경 가능 여부',
        why: '기존 저금리 대출을 새 집으로 이전할 수 있는지 확인하면 금리 혜택을 유지할 수 있습니다.',
        how: ['은행 문의', '보증기관(HUG/HF) 문의'],
        cost: '무료',
        checks: ['목적물 변경 가능 여부', '현재 소득 재심사 여부', '추가 대출 가능 여부'],
        links: [LINKS.HUG, LINKS.HF],
        showWhen: { nextHousing: ['jeonse'] },
      },
      {
        id: 'insurance-cancel',
        title: '전세보증보험 해지 절차 확인',
        why: '이사 시 기존 보증보험 계약을 종료 처리해야 하며 환급금 여부도 확인합니다.',
        how: ['HUG 또는 HF 홈페이지에서 확인', '가입한 은행 문의'],
        cost: '없음',
        checks: ['해지 절차', '환급 여부'],
        links: [LINKS.HUG, LINKS.HF],
      },
      {
        id: 'deposit-return-schedule',
        title: '기존 집 보증금 반환 일정 확인',
        why: '잔금일에 자금 공백이 생기지 않도록 기존 보증금 반환 일정을 새 집 잔금일과 맞춰야 합니다.',
        how: ['기존 임대인에게 확인'],
        cost: '없음',
        checks: ['반환 예정일', '반환 계좌', '반환 방법'],
        links: [],
      },
    ],
  },
  {
    id: 'budget-maemae',
    title: '자금 계획',
    showWhen: { nextHousing: ['maemae'] },
    items: [
      {
        id: 'total-cost-calc',
        title: '매수 총비용 계산',
        why: '매매가 외에 취득세·중개보수·법무사 비용이 추가로 발생합니다. 자금 부족으로 계약이 틀어지지 않도록 미리 계산합니다.',
        how: ['취득세 계산 (매매가 × 1~3%)', '중개보수 산정 (매매가 × 0.4~0.9%)', '법무사 비용 확인 (통상 50~100만 원)'],
        cost: '취득세 + 중개보수 + 법무사 비용',
        checks: ['취득세 예상액', '중개보수 상한 요율 확인', '법무사 비용 견적', '총 필요 자금'],
        links: [LINKS.WETAX],
        note: '1주택자 기준 취득세: 6억 이하 1%, 6~9억 1~3%, 9억 초과 3%',
      },
      {
        id: 'mortgage-check',
        title: '주택담보대출 가능 여부 확인',
        why: '계약 전 LTV·DSR 한도를 파악해야 잔금 부족 사태를 막을 수 있습니다.',
        how: ['은행 상담 또는 대출 사전심사 신청', '투기·조정·비규제지역 여부 확인'],
        cost: '무료',
        checks: ['LTV 한도 (지역·주택 수에 따라 상이)', 'DSR 40% 초과 여부', '예상 금리', '최대 대출 가능 금액'],
        links: [],
        important: true,
      },
    ],
  },
  {
    id: 'search-house',
    title: '새 집 알아보기',
    items: [
      {
        id: 'new-loan-check',
        title: '전세 대출 가능 여부 확인',
        why: '계약금을 넣기 전 대출 가능 여부를 먼저 확인해야 계약금 손실을 방지할 수 있습니다.',
        how: ['은행 상담', '사전심사 신청'],
        cost: '무료',
        checks: ['총 대출 가능 금액', '예상 금리', '추가 대출 가능 여부'],
        links: [],
        showWhen: { nextHousing: ['jeonse'] },
      },
      {
        id: 'realtor-check',
        title: '공인중개사 자격 확인',
        why: '무등록 중개업소와의 거래를 방지합니다.',
        how: ['중개사무소 등록증 확인', '브이월드에서 등록 여부 조회'],
        cost: '무료',
        checks: ['등록증 게시 여부', '개업공인중개사 성명', '등록 상태 정상 여부'],
        links: [LINKS.VWORLD],
      },
      {
        id: 'environment-check',
        title: '주변 환경 확인',
        why: '실제 거주 만족도에 큰 영향을 미칩니다. 낮과 밤 모두 방문해보세요.',
        how: ['직접 방문 (낮·밤 시간대 모두)'],
        cost: '없음',
        checks: ['대중교통 접근성', '편의점', '마트', '병원', '치안 상태', '소음 여부'],
        links: [],
      },
      {
        id: 'house-condition',
        title: '집 상태 확인',
        why: '입주 후 하자 분쟁을 방지하기 위해 방문 시 꼼꼼하게 확인합니다.',
        how: ['현장 직접 방문'],
        cost: '없음',
        checks: ['누수 흔적', '곰팡이', '결로', '창문 상태', '방충망', '수도 수압', '온수', '보일러', '에어컨', '냉장고', '세탁기'],
        links: [],
      },
      {
        id: 'maintenance-fee',
        title: '관리비 확인',
        why: '고정 지출인 관리비 구성을 미리 파악해야 실제 월 비용을 계산할 수 있습니다.',
        how: ['임대인 또는 중개사에게 문의'],
        cost: '없음',
        checks: ['월 관리비', '수도 포함 여부', '인터넷 포함 여부', '주차 포함 여부', '전기료 별도 여부', '가스비 별도 여부'],
        links: [],
      },
      {
        id: 'parking-check',
        title: '주차 가능 여부',
        why: '차량 보유 시 주차 가능 여부와 추가 비용을 사전에 확인합니다.',
        how: ['관리사무소 또는 임대인에게 문의'],
        cost: '없음',
        checks: ['주차 가능 여부', '주차 등록 필요 여부', '추가 비용 여부'],
        links: [],
      },
    ],
  },
  {
    id: 'before-contract',
    title: '계약 전',
    items: [
      {
        id: 'registry',
        title: '등기부등본 확인',
        why: '실제 소유자와 권리관계를 확인합니다.',
        how: ['인터넷등기소에서 발급'],
        cost: '약 700원',
        checks: ['소유자 확인', '근저당 확인', '압류 여부', '가압류 여부'],
        links: [LINKS.IROS],
        important: true,
      },
      {
        id: 'building-ledger',
        title: '건축물대장 확인',
        why: '불법건축물 여부를 확인합니다.',
        how: ['정부24에서 발급'],
        cost: '무료',
        checks: ['위반건축물 여부', '건물 용도 확인'],
        links: [LINKS.GOV24],
      },
      {
        id: 'tenant-status',
        title: '임차인 현황 확인',
        why: '기존 세입자가 있을 경우 잔금일까지 명도가 완료되는지 계약서에 명시해야 합니다.',
        how: ['매도인에게 임차인 유무 확인', '임대차계약서 사본 요청', '명도 일정 계약서 특약 기재'],
        cost: '무료',
        checks: ['임차인 유무', '임대차계약 잔존 기간', '명도 완료 일정 합의'],
        links: [],
        showWhen: { nextHousing: ['maemae'] },
      },
      {
        id: 'seller-tax-delinquency',
        title: '매도인 세금 체납 여부 확인',
        why: '세금 체납이 있으면 잔금 후에도 해당 주택에 압류가 들어올 수 있습니다.',
        how: ['매도인 동의 후 홈택스·위택스에서 확인'],
        cost: '무료',
        checks: ['국세 체납 여부', '지방세 체납 여부'],
        links: [LINKS.HOMETAX, LINKS.WETAX],
        important: true,
        showWhen: { nextHousing: ['maemae'] },
      },
      {
        id: 'contract-preview',
        title: '계약서 사전 확인',
        why: '계약 당일 조건이 바뀌는 것을 방지하고 특약을 미리 검토합니다.',
        how: ['공인중개사에게 초안 요청'],
        cost: '무료',
        checks: ['보증금 또는 매매가', '계약기간 또는 잔금일', '특약사항'],
        links: [],
      },
    ],
  },
  {
    id: 'contract-day',
    title: '계약 당일',
    items: [
      {
        id: 'lessor-check',
        title: '임대인·매도인 신원 확인',
        why: '실제 소유자와 계약하는지 확인합니다.',
        how: ['신분증 확인', '등기부등본 대조'],
        cost: '무료',
        checks: ['신분증 확인', '등기부등본 소유자 일치'],
        links: [],
      },
      {
        id: 'agent-check',
        title: '대리인 계약 여부 확인',
        why: '무권대리 위험을 방지합니다.',
        how: ['위임장 확인', '인감증명서 확인'],
        cost: '무료',
        checks: ['위임장 원본', '인감증명서 원본', '위임인 정보'],
        links: [],
      },
      {
        id: 'special-clause-monthly',
        title: '특약 확인',
        why: '반려동물, 흡연, 원상복구 범위 등 분쟁이 잦은 항목을 계약서에 명확히 기재합니다.',
        how: ['계약서 특약란 검토'],
        cost: '무료',
        checks: ['반려동물 가능 여부', '흡연 가능 여부', '원상복구 범위', '중도퇴실 조건', '월세 납부일', '월세 연체 시 조건'],
        links: [],
        showWhen: { nextHousing: ['monthly'] },
      },
      {
        id: 'special-clause-jeonse',
        title: '특약 확인',
        why: '대출 특약·보증보험 특약이 없으면 계약금이 보호되지 않을 수 있습니다.',
        how: ['계약서 특약란 검토'],
        cost: '무료',
        checks: ['대출 특약', '보증보험 특약', '잔금일', '반려동물 가능 여부', '원상복구 범위', '중도퇴실 조건'],
        links: [],
        showWhen: { nextHousing: ['jeonse'] },
      },
      {
        id: 'stamp-tax',
        title: '인지세 첨부',
        why: '매매계약서에는 계약금액에 따른 인지세를 납부하고 수입인지를 첨부해야 합니다.',
        how: ['계약금액 확인 후 인지세 납부', '전자수입인지 구매 (기획재정부 전자수입인지 사이트)'],
        cost: '1억~10억: 15만 원 / 10억 초과: 35만 원',
        checks: ['인지세 납부 완료', '수입인지 계약서 첨부'],
        links: [],
        note: '매수인·매도인 각 50% 부담이 원칙 (협의 가능)',
        showWhen: { nextHousing: ['maemae'] },
      },
      {
        id: 'mortgage-clause',
        title: '융자 상환·승계 특약 확인',
        why: '매도인의 기존 담보대출 처리 방식을 계약서에 명시해야 분쟁을 방지할 수 있습니다.',
        how: ['계약서 특약란에 "잔금일 전 근저당 말소" 또는 승계 조건 명시'],
        cost: '무료',
        checks: ['근저당 말소 시점 명시', '말소 비용 부담 주체', '승계 시 대출 금액·금리 확인'],
        links: [],
        important: true,
        showWhen: { nextHousing: ['maemae'] },
      },
    ],
  },
  {
    id: 'vacate-prep',
    title: '퇴거 준비',
    items: [
      {
        id: 'moving-company',
        title: '이사 업체 예약',
        why: '원하는 날짜를 확보하려면 미리 예약해야 합니다.',
        how: ['이사업체 비교 견적 후 예약'],
        cost: '업체별 상이',
        checks: ['방문 견적', '추가 비용 여부', '사다리차 필요 여부'],
        links: [],
      },
      {
        id: 'restoration',
        title: '원상복구 범위 확인',
        why: '퇴거 시 보증금에서 공제되는 항목을 미리 임대인과 협의합니다.',
        how: ['임대인과 사전 협의'],
        cost: '상황에 따라 상이',
        checks: ['벽지 훼손', '못 자국', '파손 시설'],
        links: [],
        showWhen: { currentHousing: ['monthly', 'jeonse'] },
      },
      {
        id: 'photo-record',
        title: '퇴거 전 집 상태 촬영',
        why: '퇴거 시 보증금 분쟁을 방지하기 위해 현재 상태를 사진·영상으로 기록합니다.',
        how: ['전체 공간 사진 촬영', '영상 촬영'],
        cost: '무료',
        checks: ['전체 공간 촬영', '옵션 비품 촬영', '계량기 촬영'],
        links: [],
        showWhen: { currentHousing: ['monthly', 'jeonse'] },
      },
    ],
  },
  {
    id: 'before-move-in',
    title: '새 집 최종 점검',
    items: [
      {
        id: 'registry-recheck',
        title: '등기부등본 재확인',
        why: '계약 후 권리관계가 바뀌었을 수 있습니다. 잔금 지급 전 반드시 재확인하세요.',
        how: ['인터넷등기소에서 재발급'],
        cost: '약 700원',
        checks: ['신규 근저당 여부', '신규 압류 여부', '계약 당시와 동일한 상태인지'],
        links: [LINKS.IROS],
        important: true,
      },
      {
        id: 'legal-scrivener-prep',
        title: '법무사 선임 및 서류 준비',
        why: '잔금일에 소유권이전등기를 즉시 신청하려면 법무사를 사전에 선임하고 매도인 서류를 미리 확인해야 합니다.',
        how: ['법무사 사전 선임 및 비용 견적', '매도인 필요 서류 목록 확인 (등기권리증·인감도장·인감증명서 등)'],
        cost: '법무사 보수 + 등록면허세 등 실비',
        checks: ['법무사 선임 완료', '매도인 서류 목록 확인', '잔금일 일정 조율'],
        links: [],
        showWhen: { nextHousing: ['maemae'] },
      },
      {
        id: 'final-condition',
        title: '새 집 상태 최종 점검',
        why: '입주 전 하자를 확인합니다.',
        how: ['현장 직접 방문'],
        cost: '무료',
        checks: ['누수', '곰팡이', '보일러', '수도', '전기', '옵션 정상 작동'],
        links: [],
      },
    ],
  },
  {
    id: 'move-day',
    title: '이사 당일',
    items: [
      {
        id: 'deposit-return',
        title: '현재 집 보증금 반환 확인',
        why: '보증금을 제때 돌려받지 못하면 임차권등기명령 등의 절차가 필요할 수 있습니다.',
        how: ['계좌 입금 확인'],
        cost: '없음',
        checks: ['보증금 입금 확인', '공제 내역 확인', '영수증 수령 여부'],
        links: [],
        important: true,
        showWhen: { currentHousing: ['monthly', 'jeonse'] },
      },
      {
        id: 'sell-balance-confirm',
        title: '매도 잔금 수령 확인',
        why: '잔금이 입금된 것을 확인한 후 소유권 관련 서류를 넘겨야 합니다.',
        how: ['계좌 입금 확인 후 열쇠 및 서류 인도'],
        cost: '없음',
        checks: ['잔금 입금 확인', '열쇠 및 서류 인도', '계량기 검침'],
        links: [],
        important: true,
        showWhen: { currentHousing: ['maemae'] },
      },
      {
        id: 'loan-repay',
        title: '전세대출 상환 확인',
        why: '보증금 수령 후 대출 상환이 이루어져야 합니다.',
        how: ['은행 확인'],
        cost: '없음',
        checks: ['상환 완료 여부', '잔액 확인'],
        links: [],
        showWhen: { currentHousing: ['jeonse'] },
      },
      {
        id: 'ownership-transfer',
        title: '소유권이전등기 신청',
        why: '잔금 지급과 동시에 법무사를 통해 소유권이전등기를 신청해야 내 소유권을 즉시 보호할 수 있습니다.',
        how: ['법무사를 통해 잔금과 동시에 등기 신청'],
        cost: '법무사 보수 + 등록면허세 등 실비',
        checks: ['등기 신청 완료', '등기 접수증 수령'],
        links: [],
        important: true,
        showWhen: { nextHousing: ['maemae'] },
      },
      {
        id: 'eviction-confirm',
        title: '명도 확인',
        why: '매도인 또는 임차인이 퇴거를 완료했는지 확인해야 합니다.',
        how: ['현장 방문으로 퇴거 완료 확인', '잔여 짐 없음 확인'],
        cost: '무료',
        checks: ['퇴거 완료', '잔여 짐 없음'],
        links: [],
        showWhen: { nextHousing: ['maemae'] },
      },
      {
        id: 'resident-registration',
        title: '전입신고',
        why: '전입신고를 해야 대항력이 발생합니다. 이사 당일 바로 신청하세요.',
        how: ['정부24 온라인 신청', '주민센터 방문'],
        cost: '무료',
        checks: ['전입신고 완료'],
        links: [LINKS.GOV24],
      },
      {
        id: 'fixed-date',
        title: '확정일자',
        why: '우선변제권 확보를 위해 전입신고와 함께 당일 처리합니다.',
        how: ['주민센터 방문'],
        cost: '약 600원',
        checks: ['확정일자 완료'],
        links: [LINKS.IROS],
        showWhen: { nextHousing: ['jeonse'] },
      },
      {
        id: 'maintenance-settlement',
        title: '관리비 정산 확인',
        why: '이전 세입자 사용분과 내 사용분을 구분합니다.',
        how: ['관리사무소 확인', '계량기 직접 확인'],
        cost: '없음',
        checks: ['전기 검침', '수도 검침', '가스 검침', '미납 관리비 여부'],
        links: [],
      },
      {
        id: 'key-handover',
        title: '열쇠 및 비밀번호 인수',
        why: '정상 입주에 필요한 모든 접근 수단을 확인합니다.',
        how: ['임대인 또는 관리사무소로부터 인수'],
        cost: '없음',
        checks: ['현관 열쇠', '공동현관 비밀번호', '우편함 비밀번호', '주차 등록 여부'],
        links: [],
      },
    ],
  },
  {
    id: 'after-move-in',
    title: '입주 이후',
    items: [
      {
        id: 'new-insurance',
        title: '전세보증보험 가입',
        why: '보증금 보호를 위해 입주 후 가능한 빨리 가입합니다. 전입신고·확정일자 후 신청 가능합니다.',
        how: ['HUG 또는 HF 홈페이지', '취급 은행 창구'],
        cost: '상품별 상이',
        checks: ['가입 완료', '보증서 수령'],
        links: [LINKS.HUG, LINKS.HF],
        showWhen: { nextHousing: ['jeonse'] },
      },
      {
        id: 'acquisition-tax',
        title: '취득세 납부',
        why: '잔금일로부터 60일 이내에 납부해야 합니다. 기한 초과 시 가산세가 부과됩니다.',
        how: ['위택스 온라인 납부', '관할 시·군·구청 방문 납부'],
        cost: '매매가 × 1~3% (주택 수·가격에 따라 상이)',
        checks: ['납부 기한 확인 (잔금일로부터 60일 이내)', '취득세 납부 완료', '영수증 보관'],
        links: [LINKS.WETAX],
        important: true,
        showWhen: { nextHousing: ['maemae'] },
      },
      {
        id: 'real-transaction-report',
        title: '부동산 실거래 신고 확인',
        why: '매매계약 체결 후 30일 이내 신고 의무가 있습니다. 중개사가 대리 신고하지 않은 경우 직접 신고해야 합니다.',
        how: ['공인중개사에게 신고 완료 여부 확인', '직거래 시 관할 시·군·구청에 직접 신고'],
        cost: '무료 (미신고 시 최대 500만 원 과태료)',
        checks: ['신고 완료 여부', '신고 확인서 수령'],
        links: [LINKS.MOLIT],
        showWhen: { nextHousing: ['maemae'] },
      },
    ],
  },
]
