import type { ChecklistSection } from '../../types/checklist'
import { LINKS } from '../externalLinks'

export const newHomeSections: ChecklistSection[] = [
  {
    id: 'before-search',
    title: '집 알아보기 전',
    items: [
      {
        id: 'realtor-check',
        title: '공인중개사 자격 확인',
        why: '무등록 중개업소와의 거래를 방지하고, 사고 발생 시 책임 소재를 확인하기 위해 필요합니다.',
        how: ['중개사무소 등록증 확인', '브이월드에서 등록 여부 조회', '계약서 작성자 확인'],
        cost: '무료',
        checks: ['중개사무소 등록증 게시 여부', '개업공인중개사 성명', '등록 상태 정상 여부', '계약서 서명자가 개업공인중개사인지'],
        links: [LINKS.VWORLD],
      },
    ],
  },
  {
    id: 'found-house',
    title: '마음에 드는 집을 찾았을 때',
    items: [
      {
        id: 'loan-check',
        title: '대출 확인',
        why: '계약 후 자금 부족이나 대출 불가로 인한 계약금 손실을 방지하기 위해 미리 확인해야 합니다.',
        how: ['은행 상담', '대출 사전심사 신청'],
        cost: '무료',
        checks: ['최대 대출 가능 금액', '예상 금리', '소득 기준 충족 여부', '전세대출 가능 여부'],
        links: [],
      },
      {
        id: 'existing-loan-check',
        title: '기존 전세대출 유지 가능 여부',
        why: '기존에 받은 저금리 대출을 새 집에서도 유지할 수 있는지, 목적물 변경이 가능한지 확인합니다.',
        how: ['기존 대출 은행 문의', 'HUG / HF 보증기관 문의'],
        cost: '무료',
        checks: ['목적물 변경 가능 여부', '추가 대출 가능 여부', '예상 금리', '총 필요 자금'],
        links: [LINKS.HUG, LINKS.HF],
      },
    ],
  },
  {
    id: 'before-contract',
    title: '계약 전',
    items: [
      {
        id: 'registry',
        title: '등기부등본 확인',
        why: '실제 소유자와 권리관계를 확인하고 선순위 채권 여부를 파악합니다. 가장 중요한 절차입니다.',
        how: ['인터넷등기소에서 열람·발급', '무인발급기 이용'],
        cost: '약 700원',
        checks: ['실제 소유자와 계약자 동일 여부', '근저당 설정 금액', '압류 여부', '가압류 여부', '가처분 여부', '최근 소유권 이전 이력'],
        links: [LINKS.IROS],
        important: true,
      },
      {
        id: 'building-ledger',
        title: '건축물대장 확인',
        why: '불법건축물 여부와 전세보증보험 가입 가능 여부를 사전에 확인합니다.',
        how: ['정부24에서 무료 발급', '무인발급기 이용'],
        cost: '무료',
        checks: ['위반건축물 여부', '건물 용도 확인', '불법 증축 여부'],
        links: [LINKS.GOV24],
      },
      {
        id: 'land-ledger',
        title: '토지대장 / 토지이용계획확인서',
        why: '향후 재개발·재건축 등 개발 계획을 미리 파악해 거주 환경 변화를 예측합니다.',
        how: ['정부24에서 발급'],
        cost: '무료',
        checks: ['개발제한구역 여부', '재개발 여부', '재건축 여부'],
        links: [LINKS.GOV24],
      },
      {
        id: 'tax-delinquency',
        title: '임대인 세금 체납 여부 확인',
        why: '경매 시 일부 세금이 보증금보다 우선 변제될 수 있어 반드시 확인해야 합니다.',
        how: ['임대인 동의 후 세무서 방문 또는 홈택스·위택스에서 확인'],
        cost: '무료',
        checks: ['국세 체납 여부', '지방세 체납 여부'],
        links: [LINKS.HOMETAX, LINKS.WETAX],
        important: true,
      },
      {
        id: 'jeonse-rate',
        title: '전세가율 확인',
        why: '집값 대비 전세금이 너무 높으면 깡통전세 위험이 있습니다. 80% 이상이면 주의, 90% 이상이면 위험 신호입니다.',
        how: ['국토부 실거래가 시스템에서 최근 매매가 확인', 'KB부동산, 네이버부동산 참고'],
        cost: '무료',
        checks: ['최근 매매가', '최근 전세가', '전세가율 계산 (전세가 ÷ 매매가 × 100)'],
        links: [LINKS.MOLIT, LINKS.KB, LINKS.NAVER],
        note: '전세가율 80% 이상 → 주의 / 90% 이상 → 위험 신호',
      },
      {
        id: 'insurance-available',
        title: '전세보증보험 가입 가능 여부',
        why: '가입 불가 주택을 사전에 걸러내기 위해 계약 전 확인이 필수입니다.',
        how: ['HUG 또는 HF 홈페이지에서 확인', '취급 은행 문의'],
        cost: '무료',
        checks: ['HUG 가입 가능 여부', 'HF 가입 가능 여부'],
        links: [LINKS.HUG, LINKS.HF],
        important: true,
      },
      {
        id: 'contract-preview',
        title: '계약서 사전 확인',
        why: '계약 당일 조건이 갑자기 바뀌는 것을 방지하고 특약 내용을 미리 검토합니다.',
        how: ['공인중개사에게 초안 요청', '특약 문구 사전 확인'],
        cost: '무료',
        checks: ['보증금', '계약금', '잔금일', '대출 특약', '보증보험 특약'],
        links: [],
      },
    ],
  },
  {
    id: 'contract-day',
    title: '계약 당일',
    items: [
      {
        id: 'lessor-check',
        title: '임대인 신원 확인',
        why: '실제 소유자와 계약을 체결하는지 반드시 확인해야 합니다.',
        how: ['신분증 확인', '등기부등본 소유자와 대조'],
        cost: '무료',
        checks: ['임대인 성명', '신분증 사진 대조', '등기부등본상 소유자 일치'],
        links: [],
      },
      {
        id: 'agent-check',
        title: '대리인 계약 여부 확인',
        why: '권한 없는 대리인과 계약하면 계약이 무효가 될 수 있습니다.',
        how: ['위임장 원본 확인', '인감증명서 원본 확인'],
        cost: '무료',
        checks: ['위임장 원본', '인감증명서 원본', '위임인 정보'],
        links: [],
      },
      {
        id: 'deposit-forfeit',
        title: '계약금 몰취 조건 확인',
        why: '계약 해제 시 계약금 손실을 방지하기 위해 조건을 명확히 확인합니다.',
        how: ['계약서 특약 검토'],
        cost: '무료',
        checks: ['계약 해제 조건', '계약금 반환 조건'],
        links: [],
      },
      {
        id: 'loan-clause',
        title: '대출 특약 확인',
        why: '대출이 거절될 경우 계약금을 돌려받으려면 특약에 명시되어야 합니다.',
        how: ['계약서 특약란 직접 확인 및 수정 요청'],
        cost: '무료',
        checks: ['전세자금대출 미승인 시 계약 해제 문구', '계약금 전액 반환 문구', '모호한 표현 제거'],
        links: [],
        note: '권장 문구: "임차인의 전세자금대출이 금융기관 심사 결과 승인되지 않을 경우 본 계약은 해제되며 계약금을 전액 반환한다."',
        important: true,
      },
      {
        id: 'insurance-clause',
        title: '전세보증보험 특약 확인',
        why: '임대인의 협조 없이는 보증보험 가입이 어렵습니다. 특약으로 미리 확보합니다.',
        how: ['계약서 특약란 확인'],
        cost: '무료',
        checks: ['임대인은 임차인의 전세보증보험 가입에 협조한다는 문구'],
        links: [],
      },
    ],
  },
  {
    id: 'before-balance',
    title: '잔금 지급 전',
    items: [
      {
        id: 'registry-recheck',
        title: '등기부등본 재확인',
        why: '계약 후 잔금 전 사이에 새로운 근저당이나 압류가 생길 수 있습니다. 잔금 당일 반드시 재발급해 확인하세요.',
        how: ['잔금 당일 인터넷등기소에서 재발급'],
        cost: '약 700원',
        checks: ['신규 근저당 여부', '신규 압류 여부', '신규 가압류 여부', '계약 당시와 동일한 상태인지'],
        links: [LINKS.IROS],
        important: true,
      },
      {
        id: 'house-condition',
        title: '집 상태 최종 확인',
        why: '입주 전 하자를 확인하고 계약 당시 상태가 유지되고 있는지 점검합니다.',
        how: ['현장 직접 방문'],
        cost: '무료',
        checks: ['누수', '곰팡이', '보일러', '수도', '전기', '옵션 비품', '도어락', '창문 잠금장치'],
        links: [],
      },
    ],
  },
  {
    id: 'move-in-day',
    title: '입주 당일',
    items: [
      {
        id: 'resident-registration',
        title: '전입신고',
        why: '전입신고를 해야 대항력이 생겨 집이 경매에 넘어가도 계속 거주할 수 있습니다.',
        how: ['정부24 온라인 신청', '가까운 주민센터 방문'],
        cost: '무료',
        checks: ['전입신고 완료'],
        links: [LINKS.GOV24],
      },
      {
        id: 'fixed-date',
        title: '확정일자',
        why: '확정일자를 받아야 우선변제권이 생겨 경매 시 보증금을 우선적으로 돌려받을 수 있습니다.',
        how: ['주민센터 방문', '등기소 방문'],
        cost: '약 600원',
        checks: ['확정일자 완료'],
        links: [LINKS.IROS],
      },
      {
        id: 'maintenance-settlement',
        title: '관리비 정산 확인',
        why: '이전 세입자의 미납 관리비가 새 세입자에게 청구되는 분쟁을 방지합니다.',
        how: ['관리사무소 또는 임대인에게 확인', '계량기 직접 확인'],
        cost: '없음',
        checks: ['미납 관리비 존재 여부', '계량기 검침 (전기·수도·가스)'],
        links: [],
      },
    ],
  },
  {
    id: 'after-move-in',
    title: '입주 이후',
    items: [
      {
        id: 'insurance-join',
        title: '전세보증보험 가입',
        why: '집주인이 보증금을 돌려주지 않을 경우 보증기관이 대신 지급해줍니다. 반드시 가입하세요.',
        how: ['HUG 홈페이지 또는 앱', 'HF 홈페이지', '취급 은행 창구'],
        cost: '보증금 및 상품에 따라 상이',
        checks: ['보증보험 가입 완료', '가입 기한 확인 (전입일로부터 1개월 이내)', '보증서 발급 완료'],
        links: [LINKS.HUG, LINKS.HF],
      },
    ],
  },
]
