import type { GlossaryTerm } from '../types/checklist'

export const glossaryTerms: GlossaryTerm[] = [
  { id: 'lessor', term: '임대인', category: '계약', meaning: '집주인', detail: '집을 빌려주는 사람. 보증금을 받고 임차인에게 집을 제공합니다.' },
  { id: 'lessee', term: '임차인', category: '계약', meaning: '세입자', detail: '집을 빌리는 사람. 보증금을 내고 임대인의 집에 거주합니다.' },
  { id: 'lease', term: '임대차계약', category: '계약', meaning: '집을 빌리고 빌려주는 계약', detail: '임대인과 임차인 사이에 체결하는 계약으로 보증금, 월세, 계약기간 등을 정합니다.' },
  { id: 'deposit', term: '보증금', category: '계약', meaning: '계약 시 집주인에게 맡기는 돈', detail: '전세는 전액이 보증금이고, 월세는 보증금 + 월세 형태입니다.' },
  { id: 'down-payment', term: '계약금', category: '계약', meaning: '계약 체결 시 먼저 지급하는 금액', detail: '보통 보증금의 10%. 계약금 지급 후 일방이 계약을 파기하면 계약금을 못 돌려받거나 배액을 물어야 합니다.' },
  { id: 'balance', term: '잔금', category: '계약', meaning: '계약금 제외 후 나머지 금액', detail: '보증금 1억원 기준 계약금 1000만원 납부 시 잔금은 9000만원입니다.' },
  { id: 'special-clause', term: '특약', category: '계약', meaning: '계약서에 추가로 넣는 특별 약정', detail: '대출 불가 시 계약 해제, 보증보험 가입 협조, 반려동물 허용 여부 등을 기재합니다.' },
  { id: 'tacit-renewal', term: '묵시적 갱신', category: '계약', meaning: '자동 계약 연장', detail: '계약 종료 전 2~6개월 사이에 해지 의사를 밝히지 않으면 동일 조건으로 2년 자동 연장됩니다.' },
  { id: 'renewal-right', term: '계약갱신청구권', category: '계약', meaning: '임차인이 한 번 더 계약 연장을 요구할 수 있는 권리', detail: '주택임대차보호법으로 보장되며 1회 사용 가능합니다.' },
  { id: 'registry', term: '등기부등본', category: '권리관계', meaning: '부동산의 주민등록증', detail: '실제 소유자, 근저당, 압류, 가압류 등 권리관계 전부를 확인할 수 있는 가장 중요한 서류입니다.' },
  { id: 'section-a', term: '갑구', category: '권리관계', meaning: '등기부등본에서 소유권 관련 내용', detail: '소유자, 압류, 가압류 등을 확인할 수 있습니다.' },
  { id: 'section-b', term: '을구', category: '권리관계', meaning: '등기부등본에서 채무 관련 내용', detail: '근저당, 전세권 등을 확인할 수 있습니다.' },
  { id: 'mortgage', term: '근저당', category: '권리관계', meaning: '은행이 설정한 담보권 (집주인의 빚)', detail: '채권최고액으로 기재되며 실제 대출금의 약 120% 수준입니다. 근저당이 크면 경매 시 보증금 회수가 어렵습니다.' },
  { id: 'max-credit', term: '채권최고액', category: '권리관계', meaning: '은행이 최대로 확보할 수 있는 금액', detail: '실제 대출금보다 약 120% 높게 설정됩니다.' },
  { id: 'seizure', term: '압류', category: '권리관계', meaning: '국가나 기관이 재산을 묶어놓은 상태', detail: '압류가 있으면 경매로 넘어갈 위험이 높습니다. 계약 전 반드시 확인하세요.' },
  { id: 'provisional-seizure', term: '가압류', category: '권리관계', meaning: '재판 전 재산을 임시로 묶는 조치', detail: '재판 결과에 따라 정식 압류로 이어질 수 있어 위험 신호입니다.' },
  { id: 'provisional-disposition', term: '가처분', category: '권리관계', meaning: '부동산 처분을 제한하는 법적 조치', detail: '가처분이 있는 집은 소유권 이전이 제한될 수 있으니 계약을 피하는 것이 좋습니다.' },
  { id: 'jeonse', term: '전세', category: '전세', meaning: '보증금을 맡기고 월세 없이 거주하는 방식', detail: '계약 기간 동안 월세 없이 살다가 계약 종료 시 보증금 전액을 돌려받습니다.' },
  { id: 'jeonse-loan', term: '전세대출', category: '전세', meaning: '전세보증금을 빌리는 대출', detail: '버팀목, HF, HUG 보증을 통한 대출 상품이 있으며 소득 및 주택 요건에 따라 한도가 다릅니다.' },
  { id: 'jeonse-rate', term: '전세가율', category: '전세', meaning: '집값 대비 전세금 비율', detail: '전세가 ÷ 매매가 × 100으로 계산합니다. 80% 이상이면 주의, 90% 이상이면 깡통전세 위험입니다.' },
  { id: 'empty-jeonse', term: '깡통전세', category: '전세', meaning: '집값보다 전세금이 너무 높은 상태', detail: '집값이 하락하거나 경매로 넘어갈 경우 보증금을 전부 돌려받지 못할 수 있습니다.' },
  { id: 'priority-credit', term: '선순위 채권', category: '전세', meaning: '내 보증금보다 먼저 변제받는 채권', detail: '근저당, 세금 체납 등이 해당합니다. 선순위 채권이 클수록 내 보증금이 위험합니다.' },
  { id: 'priority-repay', term: '우선변제권', category: '전세', meaning: '경매 시 보증금을 우선적으로 받을 권리', detail: '전입신고 + 확정일자를 받아야 발생합니다. 당일 처리가 중요합니다.' },
  { id: 'opposing-power', term: '대항력', category: '전세', meaning: '집이 팔려도 계속 살 수 있는 권리', detail: '전입신고 + 실제 거주가 충족되어야 발생하며, 익일 0시부터 효력이 생깁니다.' },
  { id: 'fixed-date', term: '확정일자', category: '전세', meaning: '임대차계약 체결 사실을 국가가 증명하는 날짜', detail: '주민센터 또는 등기소에서 받으며 약 600원의 수수료가 발생합니다.' },
  { id: 'hug', term: 'HUG', category: '보증보험', meaning: '주택도시보증공사', detail: '전세보증보험을 제공하는 기관입니다. 집주인이 보증금을 돌려주지 않으면 대신 지급합니다.' },
  { id: 'hf', term: 'HF', category: '보증보험', meaning: '한국주택금융공사', detail: '전세보증보험 및 전세대출 보증을 제공하는 기관입니다.' },
  { id: 'sgi', term: 'SGI', category: '보증보험', meaning: '서울보증보험', detail: '전세보증보험을 제공하는 민간 보험사입니다.' },
  { id: 'insurance', term: '전세보증보험', category: '보증보험', meaning: '집주인이 보증금을 돌려주지 않을 경우 보증기관이 대신 지급하는 보험', detail: 'HUG, HF, SGI를 통해 가입할 수 있으며 전입일로부터 1개월 이내 가입이 권장됩니다.' },
  { id: 'monthly-rent', term: '월세', category: '월세', meaning: '매달 임대료를 지급하는 방식', detail: '보증금 + 월세 형태이며 보증금이 낮을수록 월세가 높아집니다.' },
  { id: 'maintenance', term: '관리비', category: '월세', meaning: '건물 유지관리 비용', detail: '공용전기, 청소비, 승강기, 인터넷 등이 포함될 수 있습니다. 계약 전 구성 항목을 꼭 확인하세요.' },
  { id: 'half-jeonse', term: '반전세', category: '월세', meaning: '전세와 월세의 중간 형태', detail: '보증금 1억원에 월세 20만원처럼 보증금이 높고 월세가 낮은 형태입니다.' },
  { id: 'restoration', term: '원상복구', category: '이사', meaning: '입주 당시 상태로 복구하는 것', detail: '퇴거 시 못 제거, 벽지 보수 등이 해당합니다. 계약서에 범위를 명확히 기재하는 것이 좋습니다.' },
  { id: 'defect', term: '하자', category: '이사', meaning: '주택의 결함', detail: '누수, 곰팡이, 결로 등이 해당합니다. 입주 전 꼼꼼히 확인하고 하자 발생 시 임대인에게 수리를 요청할 수 있습니다.' },
  { id: 'condensation', term: '결로', category: '이사', meaning: '실내외 온도차로 물방울이 생기는 현상', detail: '곰팡이의 주요 원인입니다. 북향이나 단열이 불량한 집에서 자주 발생합니다.' },
  { id: 'move-in-report', term: '전입신고', category: '이사', meaning: '새 주소로 주민등록을 이전하는 신고', detail: '입주 당일 반드시 처리해야 대항력이 발생합니다. 정부24 또는 주민센터에서 할 수 있습니다.' },
  { id: 'lien-registration', term: '임차권등기명령', category: '이사', meaning: '이사 후에도 보증금 반환 권리를 유지하는 제도', detail: '집주인이 보증금을 돌려주지 않을 때 법원에 신청합니다. 이사 후에도 권리가 보전됩니다.' },
  { id: 'content-cert', term: '내용증명', category: '이사', meaning: '언제 어떤 내용을 보냈는지 증명하는 우편', detail: '계약 해지 통보나 보증금 반환 요청 시 활용합니다. 우체국에서 발송할 수 있습니다.' },
  { id: 'building-register', term: '건축물대장', category: '건물', meaning: '건물 정보를 기록한 문서', detail: '위반건축물 여부, 건물 용도 등을 확인할 수 있습니다. 전세보증보험 가입 가능 여부에 영향을 미칩니다.' },
  { id: 'illegal-building', term: '위반건축물', category: '건물', meaning: '건축법을 위반한 건물', detail: '위반건축물로 등재된 집은 전세대출과 보증보험 가입이 거절될 수 있습니다.' },
  { id: 'illegal-building', term: '전용면적', category: '건물', meaning: '입주자가 단독으로 사용하는 공간의 면적', detail: '벽 안쪽 기준으로 측정하며, 방·거실·주방·화장실 등이 포함됩니다.' },
  { id: 'realtor', term: '개업공인중개사', category: '중개사', meaning: '중개사무소를 운영하는 공인중개사', detail: '계약서에 날인할 수 있는 주체입니다. 계약서를 쓸 때 반드시 개업공인중개사인지 확인하세요.' },
]

export const glossaryCategories = ['계약', '권리관계', '전세', '보증보험', '월세', '이사', '건물', '중개사']
